name: Build Wails Desktop App

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install gtk+3 webkitgtk pkg-config

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Verify Installation
        run: wails doctor

      - name: Build Application (Linux/MacOS)
        if: runner.os != 'Windows'
        run: |
          wails build -clean -platform ${{ runner.os == 'Linux' && 'linux/amd64' || 'darwin/universal' }}

      - name: Build Application (Windows)
        if: runner.os == 'Windows'
        run: |
          wails build -clean -platform windows/amd64

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CAN-Finder-${{ matrix.os }}
          path: |
            build/bin/
            build/*.app
            build/*.exe
